entities/src/Entity/Catalogue.php
<?php

namespace App\Entity;

use App\Repository\CatalogueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CatalogueRepository::class)]
class Catalogue
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_date = null;

    #[ORM\ManyToOne]
    private ?categories $gender = null;

    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'catalogues')]
    private Collection $Categories;

    #[ORM\ManyToMany(targetEntity: Gender::class, mappedBy: 'relation')]
    private Collection $genders;

    public function __construct()
    {
        $this->Categories = new ArrayCollection();
        $this->genders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): static
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getGender(): ?categories
    {
        return $this->gender;
    }

    public function setGender(?categories $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategories(): Collection
    {
        return $this->Categories;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->Categories->contains($category)) {
            $this->Categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->Categories->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, Gender>
     */
    public function getGenders(): Collection
    {
        return $this->genders;
    }

    public function addGender(Gender $gender): static
    {
        if (!$this->genders->contains($gender)) {
            $this->genders->add($gender);
            $gender->addRelation($this);
        }

        return $this;
    }

    public function removeGender(Gender $gender): static
    {
        if ($this->genders->removeElement($gender)) {
            $gender->removeRelation($this);
        }

        return $this;
    }
}

entities/src/Form/CatalogueType.php
<?php

namespace App\Form;

use App\Entity\Catalogue;
use App\Entity\categories;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CatalogueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('url')
            ->add('created_date')
            ->add('gender', EntityType::class, [
                'class' => categories::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Catalogue::class,
        ]);
    }
}

entities/src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Catalogue;
use App\Form\CatalogueType;
use App\Repository\CatalogueRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/catalogue')]
class CatalogueController extends AbstractController
{
    #[Route('/', name: 'app_catalogue_index', methods: ['GET'])]
    public function index(CatalogueRepository $catalogueRepository): Response
    {
        return $this->render('catalogue/index.html.twig', [
            'catalogues' => $catalogueRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_catalogue_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $catalogue = new Catalogue();
        $form = $this->createForm(CatalogueType::class, $catalogue);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($catalogue);
            $entityManager->flush();

            return $this->redirectToRoute('app_catalogue_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('catalogue/new.html.twig', [
            'catalogue' => $catalogue,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_catalogue_show', methods: ['GET'])]
    public function show(Catalogue $catalogue): Response
    {
        return $this->render('catalogue/show.html.twig', [
            'catalogue' => $catalogue,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_catalogue_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Catalogue $catalogue, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CatalogueType::class, $catalogue);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_catalogue_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('catalogue/edit.html.twig', [
            'catalogue' => $catalogue,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_catalogue_delete', methods: ['POST'])]
    public function delete(Request $request, Catalogue $catalogue, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$catalogue->getId(), $request->request->get('_token'))) {
            $entityManager->remove($catalogue);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_catalogue_index', [], Response::HTTP_SEE_OTHER);
    }
}

entities/templates/catalogue/_delete_form.html.twig
<form method="post" action="{{ path('app_catalogue_delete', {'id': catalogue.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ catalogue.id) }}">
    <button class="btn">Delete</button>
</form>

entities/templates/catalogue/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

entities/templates/catalogue/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Catalogue{% endblock %}

{% block body %}
    <h1>Edit Catalogue</h1>

    {{ include('catalogue/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_catalogue_index') }}">back to list</a>

    {{ include('catalogue/_delete_form.html.twig') }}
{% endblock %}

entities/templates/catalogue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue index{% endblock %}

{% block body %}
    <h1>Catalogue index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Url</th>
                <th>Created_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for catalogue in catalogues %}
            <tr>
                <td>{{ catalogue.id }}</td>
                <td>{{ catalogue.url }}</td>
                <td>{{ catalogue.createdDate ? catalogue.createdDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_catalogue_show', {'id': catalogue.id}) }}">show</a>
                    <a href="{{ path('app_catalogue_edit', {'id': catalogue.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_catalogue_new') }}">Create new</a>
{% endblock %}

entities/templates/catalogue/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Catalogue{% endblock %}

{% block body %}
    <h1>Create new Catalogue</h1>

    {{ include('catalogue/_form.html.twig') }}

    <a href="{{ path('app_catalogue_index') }}">back to list</a>
{% endblock %}

entities/templates/catalogue/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue{% endblock %}

{% block body %}
    <h1>Catalogue</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ catalogue.id }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ catalogue.url }}</td>
            </tr>
            <tr>
                <th>Created_date</th>
                <td>{{ catalogue.createdDate ? catalogue.createdDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_catalogue_index') }}">back to list</a>

    <a href="{{ path('app_catalogue_edit', {'id': catalogue.id}) }}">edit</a>

    {{ include('catalogue/_delete_form.html.twig') }}
{% endblock %}